# Generated by Django 5.2 on 2025-04-26 01:39

import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('new_value', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('change_reason', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('edited_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_type', models.CharField(choices=[('CRD', 'Completely Randomized Design'), ('RBD', 'Randomized Block Design'), ('LSD', 'Latin Square Design'), ('Other', 'Other Design')], max_length=50)),
                ('independent_variables', mdeditor.fields.MDTextField()),
                ('dependent_variables', mdeditor.fields.MDTextField()),
                ('control_variables', mdeditor.fields.MDTextField()),
                ('planned_methods', mdeditor.fields.MDTextField()),
                ('notes', mdeditor.fields.MDTextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('background', mdeditor.fields.MDTextField()),
                ('goal', mdeditor.fields.MDTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Running', 'Running'), ('Completed', 'Completed Successfully'), ('Failed', 'Failed')], default='Planned', max_length=20)),
                ('failure_reason', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('failure_stage', models.CharField(blank=True, choices=[('Setup', 'Setup Failure'), ('Execution', 'Execution Failure'), ('Data Collection', 'Data Collection Failure'), ('Post Processing', 'Post Processing Failure'), ('Unknown', 'Unknown/Multiple Stages')], max_length=50, null=True)),
                ('experimental_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='scientificmethod.experimentalplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', mdeditor.fields.MDTextField()),
                ('stage', models.CharField(choices=[('Setup', 'Setup Failure'), ('Execution', 'Execution Failure'), ('Data Collection', 'Data Collection Failure'), ('Post Processing', 'Post Processing Failure'), ('Unknown', 'Unknown/Multiple Stages')], max_length=50)),
                ('corrective_action', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_logs', to='scientificmethod.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', mdeditor.fields.MDTextField()),
                ('hypothesis_type', models.CharField(choices=[('Null', 'Null Hypothesis (H₀)'), ('Alternative', 'Alternative Hypothesis (H₁)')], max_length=20)),
                ('scientific_basis', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('expected_outcome', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Testing'), ('Supported', 'Supported by Data'), ('Refuted', 'Refuted by Data'), ('Modified', 'Modified after Results')], default='Pending', max_length=20)),
                ('modification_notes', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('parent_hypothesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_hypotheses', to='scientificmethod.hypothesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experimentalplan',
            name='hypothesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_plans', to='scientificmethod.hypothesis'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('result_support', models.CharField(choices=[('Support', 'Supports Hypothesis'), ('Refute', 'Refutes Hypothesis'), ('Inconclusive', 'Inconclusive Result')], default='Inconclusive', max_length=20)),
                ('notes', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scientificmethod.experiment')),
                ('hypothesis_tested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='scientificmethod.hypothesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HypothesisRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rationale_for_change', mdeditor.fields.MDTextField()),
                ('new_hypothesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_from_revision', to='scientificmethod.hypothesis')),
                ('original_hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scientificmethod.hypothesis')),
                ('based_on_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientificmethod.observation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', mdeditor.fields.MDTextField()),
                ('rationale', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('research_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scientificmethod.researchproblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='research_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses', to='scientificmethod.researchquestion'),
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('variable_type', models.CharField(choices=[('Independent', 'Independent Variable'), ('Dependent', 'Dependent Variable'), ('Confounding', 'Confounding Variable')], max_length=50)),
                ('measurement_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='scientificmethod.experiment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='scientificmethod.variable'),
        ),
    ]
